### ISSUE TITLE
Primitive parameters as a list in body on a POST fail

### ISSUE THREAD

**Issue by jerodvenemafm** [abelsilva/swaggerwcf#94] opened 2017-08-26 05:19 UTC
Given:

[WebInvoke(Method = "POST", ResponseFormat = WebMessageFormat.Json, UriTemplate = "/reports/share/{reportId}")]
public MultipleResult<Report> SaveSharedReport(string reportId, List<int> customers)

we get a failure. It attempts to add an item that doesn't conform to the spec properly, throwing exceptions when using the npm swagger-validate package. The return type doesn't matter, just having a primitive list in addition to a query param throws things out of whack.

**Comment by abelsilva** [comment] 2017-09-21 22:47
what is the `type` of that `List customers` ??

**Comment by jerodvenemafm** [comment] 2017-09-21 23:55
sorry, that was a List<int> customers

**Comment by abelsilva** [comment] 2017-09-26 22:28
Can't reproduce....

![image](https://user-images.githubusercontent.com/1167088/30887195-af5f32b0-a2f0-11e7-90b7-93b5d784ce5a.png)

Interface:
```
        [SwaggerWcfPath("Save Report", "Save Report")]
        [WebInvoke(Method = "POST", ResponseFormat = WebMessageFormat.Json, UriTemplate = "/reports/share/{reportId}")]
        [OperationContract]
        string SaveSharedReport(string reportId, List<int> customers);
```

Class:
```
        [SwaggerWcfTag("Report")]
        [SwaggerWcfResponse(HttpStatusCode.Created, "Report saved")]
        public string SaveSharedReport(string reportId, List<int> customers)
        {
            return "...";
        }
```

**Comment by abelsilva** [comment] 2017-10-30 23:25
closing, reopen if you have more details

**Closed by abelsilva** 2017-10-30 23:25 UTC
